jobs:
  main:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Fetch Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./ci/run

name: Main

on:
  schedule:
    - cron: "5 */6 * * *"
